### ISSUE TITLE
 'reset_default_graph'

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [som2603/DEM-PhaseField#1]
Hi!

tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

How can I fix this error?

**Comment by canitesc** [comment]
Hi, this code requires Tensorflow 1.15. If you are using Anaconda, I would recommend to create a Tensorflow 1 environment with 
```
conda create --name tf1 tensorflow=1.15
conda activate tf1
pip install pyevtk
pip install geomdl
...
```
