### ISSUE TITLE
IndexError: index 6 is out of bounds for axis 0 with size 

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [som2603/DEM-PhaseField#4]
Dear Somdatta @somdattagoswami,

I would like to report a "bug" from DEM-PhaseField, namely:

If we increase the degree order fron one to two (, three, ...) as follows:
```

# Set degrees
        geomData['degree_u'] = 2
        geomData['degree_v'] = 2
        
        # Set control points
        geomData['ctrlpts_size_u'] = 3
        geomData['ctrlpts_size_v'] = 3
        
        geomData['ctrlpts'] = np.array([[self.x1, self.y1, 0], [0.5*self.x2, self.y2, 0], [self.x2, self.y2, 0],
                        [self.x3, self.y3, 0], [0.5*self.x4, self.y4, 0], [self.x4, self.y4, 0]])

        geomData['weights'] = np.array([[1.0], [1.0],[1.0],[1.0], [1.0], [1.0]])
        
        # Set knot vectors
        geomData['knotvector_u'] = [0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
        geomData['knotvector_v'] = [0.0, 0.0, 0.0, 1.0, 1.0, 1.0]

```
DEM-PhaseField simulation will break, and report us:

```

  File "G:\DEM-PhaseField-master\Phase-Field\utils\BezExtr.py", line 390, in getDerivatives
    curPts = np.squeeze(self.ctrlpts[curNodes,0:2])

IndexError: index 6 is out of bounds for axis 0 with size 6
```
**IndexError: index 6 is out of bounds for axis 0 with size 6**

Also, geomData['degree_u'] = 2 seems to be the necessary conditions for the used numerical examples (the reference article).

Thanks a lot for your support in advance!

Kind regards, 
Libo

**Comment by somdattagoswami** [comment]
Dear Libo,

We have used 2nd order polynomial to represent the geometry of the problem. In case you want to change the order of the polynomial, the number of control points, and their corresponding weights need to be changed. The number of control points = degree of polynomial + 1.  Increasing the degree for this example will not change the results since the splines are only used to model the geometry, not for the approximation.

With regards,
Somdatta Goswami

**Comment by asdasdqwdqwfsdf** [comment]
Dear Somdatta @somdattagoswami,

I have already changed **the order** of the polynomial, **the number** of control points, and their **corresponding weights** for this example, not only the order for this example.  You may check the same modified code again:

```
# Set degrees
        geomData['degree_u'] = 2
        geomData['degree_v'] = 2
        
        # Set control points
        geomData['ctrlpts_size_u'] = 3
        geomData['ctrlpts_size_v'] = 3
        
        geomData['ctrlpts'] = np.array([[self.x1, self.y1, 0], [0.5*self.x2, self.y2, 0], [self.x2, self.y2, 0],
                        [self.x3, self.y3, 0], [0.5*self.x4, self.y4, 0], [self.x4, self.y4, 0]])

        geomData['weights'] = np.array([[1.0], [1.0],[1.0],[1.0], [1.0], [1.0]])
        
        # Set knot vectors
        geomData['knotvector_u'] = [0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
        geomData['knotvector_v'] = [0.0, 0.0, 0.0, 1.0, 1.0, 1.0]

```

Best reagrds,
Libo

**Comment by canitesc** [comment]
Dear Libo,

If you want to increase the degree to 2 in both directions, then you will need 9 control points and weights  in total, but you only have 6. With the 6 control points you listed, you can do degree_u=2 and degree_v=1, i.e.

       ```
        # Set degrees
        geomData['degree_u'] = 2
        geomData['degree_v'] = 1
        
        # Set control points
        geomData['ctrlpts_size_u'] = 3
        geomData['ctrlpts_size_v'] = 2
        
        geomData['ctrlpts'] = np.array([[self.x1, self.y1, 0], [0.5*self.x2, self.y2, 0], [self.x2, self.y2, 0],
                        [self.x3, self.y3, 0], [0.5*self.x4, self.y4, 0], [self.x4, self.y4, 0]])

        geomData['weights'] = np.array([[1.0], [1.0],[1.0],[1.0], [1.0], [1.0]])
        
        # Set knot vectors
        geomData['knotvector_u'] = [0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
        geomData['knotvector_v'] = [0.0, 0.0, 1.0, 1.0]
```

**Comment by asdasdqwdqwfsdf** [comment]
> 
> 
> Dear Libo,
> 
> We have used 2nd order polynomial to represent the geometry of the problem. In case you want to change the order of the polynomial, the number of control points, and their corresponding weights need to be changed. The number of control points = degree of polynomial + 1. Increasing the degree for this example will not change the results since the splines are only used to model the geometry, not for the approximation.
> 
> With regards,
> Somdatta Goswami

Dear Cosmin @canitesc, 

as  @somdattagoswami metioned,   2nd order polynomial has been used in your work & article.

If we check the provided code, from this example.

```
        # Set degrees
        geomData['degree_u'] = 1
        geomData['degree_v'] = 1
        
        # Set control points
        geomData['ctrlpts_size_u'] = 2
        geomData['ctrlpts_size_v'] = 2

```
If the **degree_u is set to 1**,  how can we have **2nd order polynomial** for C1 example?

Actually, we need **p=2**, ->

_"The convention we will adopt is that the order p = 0,1,2,3, etc., refers to constant, linear, quadratic,
cubic, etc., piecewise polynomials, respectively. This is the usual terminology in the finite element literature.
What we refer to as ‘‘order’’ is usually referred to as ‘‘degree’’ in the computational geometry literature." (10.1016/j.cma.2004.10.008)_
