### ISSUE TITLE
a multi patch NURBS example

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [som2603/DEM-PhaseField#6]
Hi @somdattagoswami 

is it possible to have some **multi patch** NURBS examples for DEM-PhaseField?

Thanks a lot in advance!

Best regards!
Libo

**Comment by somdattagoswami** [comment]
Hi Libo Yan,

It is easy to add more complicated geometries since one does not need the patch connectivity, but finding the right parameters for the model may take some work.

With Regards,
Somdatta Goswami
