### ISSUE TITLE
Why the energy_u function is different from the equations in Article?

### ISSUE THREAD

**Issue by Honghui-Du** [som2603/DEM-PhaseField#7]
I found that Eq. 24 in your article [[10.1016/j.tafmec.2020.102527](https://doi.org/10.1016/j.tafmec.2020.102527)](url) for elastic energy is different from "net_energy" function, which is 
![2b90ee11c8bc6cd06dec40a6a959923](https://user-images.githubusercontent.com/116039765/197070044-321268bb-9753-4b27-9412-49348c41ee13.jpg). Specifically, the degradation function should be imposed only on the tensile energy but it has been imposed on the whole elastic energy (if I didn't misunderstand). 

This makes me confused, hope to hear from you. 
Your help is highly appreciated!

**Comment by somdattagoswami** [comment]
In tensile loading, the strain decomposition is not required.

**Comment by Honghui-Du** [comment]
> In tensile loading, the strain decomposition is not required.

Thanks for your quick reply! Do you mean they are the same with each other? If I decompose the strain energy density into two parts and let the degradation function "g" only multiply the tensile part and sum them up, the outcome won't change?

**Comment by somdattagoswami** [comment]
In tesnile loading problems, the compressive components is zero.
